export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST"
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS"
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED"

export const DECREASE_LIST_ITEM = "DECREASE_LIST_ITEM"
export const INCREASE_LIST_ITEM = "INCREASE_LIST_ITEM"


