export const SET_INFO = 'SET_INFO'
export const OPEN_INFO = 'OPEN_INFO'
export const CLOSE_INFO = 'CLOSE_INFO'


export const OPEN_ORDER = 'OPEN_ORDER'
export const CLOSE_ORDER = 'CLOSE_ORDER'

export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS"
export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST"
export const POST_ORDER_FAILED = "POST_ORDER_FAILED"